Add e2e test for the glue script
SUSE/qe-sap-deployment pull request #228
Opened 2024-05-08 09:32 UTC by mpagot

Add a bash script and some conf.yaml to try different behaviors of the qesap.py script.

2024-05-08 14:10 UTC, alvarocarvajald approved these changes
LGTM, but I added some suggestions.

2024-05-08 14:10 UTC, alvarocarvajald commented on scripts/qesap/test/e2e/test.sh
> +! qesap.py --verbose -b ${QESAPROOT} -c test_1.yaml configure || test_die "Should exit with non zero rc but was not"
Suggestion:
```
qesap.py --verbose -b ${QESAPROOT} -c test_1.yaml configure && test_die "Should exit with non zero rc but was not"
```

2024-05-08 14:10 UTC, alvarocarvajald commented on scripts/qesap/test/e2e/test.sh
> +fi
Suggestion:
```
[[ -f "${TEST_TERRAFORM_TFVARS}" ]] || test_die "Generated file ${TEST_TERRAFORM_TFVARS} not found!"
```

2024-05-08 14:10 UTC, alvarocarvajald commented on scripts/qesap/test/e2e/test.sh
> +grep lampone "${TEST_TERRAFORM_TFVARS}" || test_die "${TEST_TERRAFORM_TFVARS} generated from test_2.yaml should contain the world lampone"
Do we need the output from `grep`? If not, then this could be `grep -q`

2024-05-08 14:10 UTC, alvarocarvajald commented on scripts/qesap/test/e2e/test.sh
> +fi
Suggestion:
```
[[ -f "${TEST_ANSIBLE_MEDIA}" ]] || test_die "Generated file ${TEST_ANSIBLE_MEDIA} not found!"
```

2024-05-08 14:10 UTC, alvarocarvajald commented on scripts/qesap/test/e2e/test.sh
> +grep corniolo "${TEST_ANSIBLE_MEDIA}" || test_die "${TEST_ANSIBLE_MEDIA} generated from test_3.yaml should contain the corniolo"
Same question regarding output from `grep` as above.

2024-05-08 14:10 UTC, alvarocarvajald commented on scripts/qesap/test/e2e/test.sh
> +fi
Suggestion:
```
[[ -f "${TEST_TERRAFORM_TFSTATE}" ]] || test_die "Generated file ${TEST_TERRAFORM_TFSTATE} not found!"
```

2024-05-09 06:28 UTC, BillAnastasiadis approved these changes
LGTM

2024-05-09 06:42 UTC, jankohoutek requested changes

2024-05-09 06:42 UTC, jankohoutek commented on scripts/qesap/test/e2e/test.sh
> +  echo "DIE : $1"
Would be fine, if this always includes return code of the failed command  `$?`

`echo "DIE($?)  :  $1"`

2024-05-09 09:02 UTC, merged