Fix azure sbd stonith-timeout
SUSE/qe-sap-deployment pull request #290
Opened 2024-11-07 13:08 UTC by BillAnastasiadis

As discovered by @jankohoutek , stonith-timeout was set erroneously for both azure sbd and native fencing cases. This pr attempts to fix that.

2024-11-07 15:27 UTC, alvarocarvajald approved these changes
LGTM

2024-11-08 08:51 UTC, jankohoutek requested changes
There is stil thet typo `[sdb]` instreadd of `[sbd]` on line 42

2024-11-11 08:52 UTC, mpagot approved these changes
LGTM

2024-11-11 11:53 UTC, mpagot approved these changes
LGTM

2024-11-11 12:49 UTC, merged